---
title: "Canadian online survey on fundamental research"
author: ""
date: "16 September 2016"
output:
  pdf_document: null
  fig_width: 18
  html_document: default
  fig_height: 4
---

**Introduction**
In addition to the official data presented in Chapters 2 and 3, we also developed and ran a quantitative online survey to query Canadian researchers about their perceptions of, and experiences with, funding for fundamental research. An important aim of the survey was to provide an understanding researcher's personal experiences and outlook on the research funding landscape in Canada. We had an excellent response to the survey, with over 1300 Canadian researchers completing it, suggesting that fundamental research funding is a high priority topic for Canadian researchers. Herein, we detail the survey questions and results. 

**Methods**  
Online Survey  
The survey was open to researchers from all disciplines (e.g. science, social sciences, humanities, engineering, medicine) and career stages, with the proviso that they had some experience applying for research funding. The survey gathered detailed information in four major areas: 1) the types of research the scholars conduct (fundamental, use-inspired, applied), 2) the extent of external partnerships in their research, 3) their grant success rates, and 4) their perceived importance of fundamental research to the Canadian federal government and of its future prospects in Canada. The survey also enquired how each of these factors have changed over time. Finally, the survey gathered basic information from each respondent about gender, discipline, career stage and the year their PhD was obtained. The full survey is provided in Appendix XX. 

The online survey was open from the end of May through early October 2016, and ran on the Fluid Surveys platform (fluidsurveys.com). Note that the survey was open to researchers from any country in the world because it is was run as part of a global survey through the Global Young Academy. To disseminate the survey to Canadian researchers, we gathered email addresses from Canadian university websites for as many faculty members as possible and emailed individual researchers directly. We also shared the survey broadly on social media, as well as through the Global Young Academy network, on scientific list serves, and through personal connections. 

Survey Data Analysis  
To extract survey responses for Canadian researchers, we selected all respondents who reported 'Canada' as their country of work, as well as those respondents who did not report a country of work (i.e. field was blank) but whose location was within Canada. We conducted all statistical analyses in the open source software R.....

<!-- Import Canadian data and calculate sample sizes -->
```{r, echo=FALSE, warning=FALSE, message=FALSE} 
##setwd("/Users/Julia_2013MacBookAir/Desktop/GitRepos/gya-research")
## load in survey data
survey<-read.csv(file="../data/gya-without-incomplete.csv")
n.Cdn.res <- survey[survey$Country_work=="Canada" | (!(survey$Country_work=="Canada") & 
             survey$Country_work=="" & survey$Country=="Canada"),]  #Count how many responses from Canadian researchers

n.Cdn.res.men <- n.Cdn.res[n.Cdn.res$gender=="Male",]               #Count how many responses from Canadian male researchers
percent.men<-((dim(n.Cdn.res.men)[1])/(dim(n.Cdn.res)[1]))*100      #Calculate the % of responses from Canadian male researchers
n.Cdn.res.women <- n.Cdn.res[n.Cdn.res$gender=="Female",]           #Count how many responses from Canadian female researchers
percent.women<-((dim(n.Cdn.res.women)[1])/(dim(n.Cdn.res)[1]))*100  #Calculate the % of responses from Canadian female researchers

n.Cdn.seniorac <- n.Cdn.res[n.Cdn.res$what_participant_group=="Senior academic researcher with >10 years of experience applying for research grants",]
percent.seniorac<-((dim(n.Cdn.seniorac)[1])/(dim(n.Cdn.res)[1]))*100 #Calculate the % of responses from Canadian senior academic researchers
n.Cdn.earlyac <- n.Cdn.res[n.Cdn.res$what_participant_group=="Early career academic researcher with <10 years experience applying for research grants since completion of PhD",]
percent.earlyac<-((dim(n.Cdn.earlyac)[1])/(dim(n.Cdn.res)[1]))*100 #Calculate the % of responses from Canadian early academic researchers
```


**Results**
In total, `r dim(n.Cdn.res)[1]` Canadian researchers completed the online survey. Of these, almost three quarters were male (`r ceiling(percent.men)`%) and one quarter were female (`r round(percent.women)`%); a very small proportion either did not input their gender or selected other. Almost all of the survey respondents (`r round(sum(percent.seniorac,percent.earlyac))`%) were either senior academics (`r round(percent.seniorac)`%), defined as those researchers with more than ten years experience applying for research grants since completion of their PhD, or early career academics (`r round(percent.earlyac)`%) (Figure 4.1). 

 <!-- Female 318 / 1283; Male 946/1283  ECR: 367 / 1283; Non-academic ECR: 7; Non-academic >10yrs: 15; Post-doc: 48; Senior: 841 (65.5%); 5 no responses; Engineering 163 (12.7%); Inter 70 (5.48%); Med/Life Sci 251(19.65%); Natural 377 (29.5%); Other 3; Phys 382 (29.9%); Social 37. For some unknown reason this totals 1277; -->
 
